### ISSUE TITLE
MobStacker error

### ISSUE THREAD

**Issue by fluxzshaaa** [Jet315/MobStacker#1]
[22:09:50 ERROR]: Could not pass event EntityDeathEvent to MobStacker v1.0
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:379) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.EntityLiving.die(EntityLiving.java:815) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:750) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.EntityAnimal.damageEntity(SourceFile:145) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.EntityLiving.C(EntityLiving.java:168) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.EntityInsentient.C(EntityInsentient.java:117) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.Entity.h(Entity.java:265) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.EntityLiving.h(EntityLiving.java:1375) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.EntityInsentient.h(EntityInsentient.java:156) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1676) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1643) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1491) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:511) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:766) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:307) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:643) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:549) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
Caused by: java.lang.NoSuchFieldError: ARMOR_STAND
        at me.jet315.stacker.events.OnEntityDeath.onEntityDeath(OnEntityDeath.java:27) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[PaperSpigot-1.7.10-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-1f7d532]
        ... 21 more

Idk, im using this on 1.7.10 paperspigot LATEST. I guess its just not compactible with that version?

**Comment by Jet315** [comment]
Hey,

Sorry for the late reply, yea 1.7 is not supported *It is like, 5 year old software*
I am able to fix this though if you would like a custom version that is 1.7 supported - PM me on the Spigot Forums if you would like that and I'll compile you a version that is supported.
